In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

Using TensorFlow backend.


In [14]:
df = pd.read_json('wine.json')
df = df.fillna(0)
df.head()

alcohol  chlorides  citric_acid  density  fixed_acidity  \
0      9.4      0.076         0.00   0.9978            7.4   
1      9.8      0.098         0.00   0.9968            7.8   
2      9.8      0.092         0.04   0.9970            7.8   
3      9.8      0.075         0.56   0.9980           11.2   
4      9.4      0.076         0.00   0.9978            7.4   

   free_sulfur_dioxide    pH  quality  residual_sugar style  sulphates  \
0                 11.0  3.51        5             1.9   red       0.56   
1                 25.0  3.20        5             2.6   red       0.68   
2                 15.0  3.26        5             2.3   red       0.65   
3                 17.0  3.16        6             1.9   red       0.58   
4                 11.0  3.51        5             1.9   red       0.56   

   total_sulfur_dioxide  volatile_acidity  
0                  34.0              0.70  
1                  67.0              0.88  
2                  54.0              0.76  
3                  60.0              0.28  
4                  34.0              0.70

In [3]:
scaler = preprocessing.StandardScaler()
columns = df.columns[0:12]
df[columns] = scaler.fit_transform(df[columns])
df.head()

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0       0.142473          2.188833    -2.192833       -0.744778   0.569958   
1       0.451036          3.282235    -2.192833       -0.597640   1.197975   
2       0.451036          2.553300    -1.917553       -0.660699   1.026697   
3       3.073817         -0.362438     1.661085       -0.744778   0.541412   
4       0.142473          2.188833    -2.192833       -0.744778   0.569958   

   free_sulfur_dioxide  total_sulfur_dioxide   density        pH  sulphates  \
0            -1.100140             -1.446359  1.034993  1.813090   0.193097   
1            -0.311320             -0.862469  0.701486 -0.115073   0.999579   
2            -0.874763             -1.092486  0.768188  0.258120   0.797958   
3            -0.762074             -0.986324  1.101694 -0.363868   0.327510   
4            -1.100140             -1.446359  1.034993  1.813090   0.193097   

    alcohol   quality style  
0 -0.915464 -0.937230   red  
1 -0.580068 -0.937230   red  
2 -0.580068 -0.937230   red  
3 -0.580068  0.207999   red  
4 -0.915464 -0.937230   red

In [5]:
label_encoder = preprocessing.LabelEncoder()
le = label_encoder.fit_transform(df['style'])
print(le)

[0 0 0 ... 1 1 1]


In [7]:
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:12], le, test_size=0.33, random_state=8)

In [8]:
# Initialize the constructor
model=Sequential()
# Add an input layer 
model.add(Dense(13, activation='relu', input_shape=(12,)))

# Add one hidden layer 
model.add(Dense(60, activation='relu'))
model.add(Dense(30, activation='relu'))

# Add an output layer 
model.add(Dense(1, activation='relu'))

model.output_shape
# Model summary
model.summary()

W0804 11:15:04.397191 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0804 11:15:04.419124 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0804 11:15:04.423113 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 13)                169       
_________________________________________________________________
dense_2 (Dense)              (None, 60)                840       
_________________________________________________________________
dense_3 (Dense)              (None, 30)                1830      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 31        
Total params: 2,870
Trainable params: 2,870
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])
model.fit(X_train, y_train,epochs=400, batch_size=100, verbose=0, callbacks=[EarlyStopping(monitor='acc', patience=200)])

W0804 11:15:22.875810 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0804 11:15:22.906729 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0804 11:15:22.915704 19396 deprecation.py:323] From C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0804 11:15:23.145091 19396 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add in

In [10]:
# over the training set
y_pred=model.predict_classes(X_train)
print(confusion_matrix(y_train, y_pred))
print(classification_report(y_train, y_pred))

[[1060   10]
 [   1 3281]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99      1070
           1       1.00      1.00      1.00      3282

   micro avg       1.00      1.00      1.00      4352
   macro avg       1.00      1.00      1.00      4352
weighted avg       1.00      1.00      1.00      4352



In [11]:
# over the test set
y_pred=model.predict_classes(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 521    8]
 [   3 1613]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       529
           1       1.00      1.00      1.00      1616

   micro avg       0.99      0.99      0.99      2145
   macro avg       0.99      0.99      0.99      2145
weighted avg       0.99      0.99      0.99      2145

